### ISSUE TITLE
Deploy Sync 0.1

### ISSUE THREAD

**Issue by dvush** [matter-labs/zksync#158]
known issues/todos:

- [x] deploy, test zksync.js with default provider for Rinkeby
- [x] long wait time for exodus (?)

issues:
- [x] something does not work in the eth sender
- [x] client does not work because of the mixed content
- [x] ethers - zksync.js versions can be different(moved to issue)

simple:
- [x] get all tokens endpoint
- [x] limit number of withdraws
- [x] Links for testnet demo / alpha notifications
- [x] lib links to github in docs
- [x] add FAU token

tweaks:
- [x] withdraw to should be to eth address and not to wallet.
- [x] utils for eth fee estimate for priority ops
- [x] full exit annoying critical bug  - still irrecoverably crashes(!) with with some user provided input (linked to #154) 

for future:
- [x] only one tx is in flight because of `eth_sender` and infura interactions.

---
- [ ] loadtest after deploy (moved to #162 )
- [ ] No withdraw in block explorer (moved to #161 )
